project:
  type: website
  output-dir: docs
  
website:
  title: "Yasmine.githhub.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Data introduction 
      - href: data_analysis.qmd
        text: Data analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

