---
title: "India's car market"
---
### Background into India's car market

When it comes to buying a new car, Indian consumers will root more for mileage than engine power. 60% of buyers want a fuel-efficient car (can be seen through high mileage) and 72% are looking to save money. Indian customers are seriously worried about fluctuating fuel prices and a good 60% don't expect fuel price stability in the next 12 months (from August 2023). They believe that fuel prices will remain too high hence the choice for a fuel-efficient car to save fuel costs.

Also many of the bigger cities in this region boast 100 million plus population so congestion is a problem. People are realising that power packed vehicles cannot be driven in the cities in this region hence the focus on fuel efficiency.

The lemon market in India is a huge problem due to information asymmetry between buyers and sellers. This asymmetry means that buyers are unable to access sufficient vehicle information, enabling sellers to exploit uninformed buyers by selling lower-quality cars. In summary, market failure (distortions in true value of the product) caused by adverse selection and moral hazard is a significant problem for many innocent buyers in India where cost is an influential factor in decision-making.

Links for reference: <br> https://auto.economictimes.indiatimes.com/news/industry/what-indian-consumers-prefer-the-most-while-buying-a-car/53825945
<br> https://www.atlantis-press.com/article/125971556.pdf
<br>